# Generated by Django 2.1.7 on 2019-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190323_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='description',
            new_name='mission',
        ),
        migrations.AddField(
            model_name='organization',
            name='link',
            field=models.CharField(default='#', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
    ]
