# Generated by Django 2.1.7 on 2019-03-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='eventimages')),
                ('i_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evelist.Event')),
            ],
        ),
    ]
