# Generated by Django 2.1.7 on 2019-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='fist_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_name',
        ),
    ]
